In [40]:
df <- read.csv('athlete_events.csv')

In [44]:
df

       ID     Name                               Sex Age Height Weight
1       1     A Dijiang                          M   24  180    80
2       2     A Lamusi                           M   23  170    60
3       3     Gunnar Nielsen Aaby                M   24   NA    NA
4       4     Edgar Lindenau Aabye               M   34   NA    NA
5       5     Christine Jacoba Aaftink           F   21  185    82
6       5     Christine Jacoba Aaftink           F   21  185    82
7       5     Christine Jacoba Aaftink           F   25  185    82
8       5     Christine Jacoba Aaftink           F   25  185    82
9       5     Christine Jacoba Aaftink           F   27  185    82
10      5     Christine Jacoba Aaftink           F   27  185    82
11      6     Per Knut Aaland                    M   31  188    75
12      6     Per Knut Aaland                    M   31  188    75
13      6     Per Knut Aaland                    M   31  188    75
14      6     Per Knut Aaland                    M   31  188    75
15      6     Per Knut Aaland                    M   33  188    75
16      6     Per Knut Aaland                    M   33  188    75
17      6     Per Knut Aaland                    M   33  188    75
18      6     Per Knut Aaland                    M   33  188    75
19      7     John Aalberg                       M   31  183    72
20      7     John Aalberg                       M   31  183    72
21      7     John Aalberg                       M   31  183    72
22      7     John Aalberg                       M   31  183    72
23      7     John Aalberg                       M   33  183    72
24      7     John Aalberg                       M   33  183    72
25      7     John Aalberg                       M   33  183    72
26      7     John Aalberg                       M   33  183    72
27      8     Cornelia "Cor" Aalten (-Strannood) F   18  168    NA
28      8     Cornelia "Cor" Aalten (-Strannood) F   18  168    NA
29      9     Antti Sami Aalto                   M   26  186    96
30     10     Einar Ferdinand "Einari" Aalto     M   26   NA    NA
â‹®      â‹®      â‹®                                  â‹®   â‹®   â‹®      â‹®
271087 135555 Micha Zych                         M   23  177    68
271088 135556 Bogusaw Stanisaw Zychowicz         M   19  189    80
271089 135556 Bogusaw Stanisaw Zychowicz         M   19  189    80
271090 135557 Dominik ycki                       M   34  192    95
271091 135557 Dominik ycki                       M   38  192    95
271092 135558 ukasz Tomasz ygado                 M   32  200    89
271093 135559 Pawe Jan Zygmunt                   M   21  182    79
271094 135559 Pawe Jan Zygmunt                   M   21  182    79
271095 135559 Pawe Jan Zygmunt                   M   25  182    79
271096 135559 Pawe Jan Zygmunt                   M   25  182    79
271097 135559 Pawe Jan Zygmunt                   M   29  182    79
271098 135559 Pawe Jan Zygmunt                   M   29  182    79
271099 135559 Pawe Jan Zygmunt                   M   33  182    79
271100 135560 Stavroula Zygouri                  F   36  171    63
271101 135561 Frantiek Zyka                      M   26   NA    NA
271102 135562 Milan Zyka                         M   24  173    68
271103 135563 Olesya Nikolayevna Zykina          F   19  171    64
271104 135563 Olesya Nikolayevna Zykina          F   23  171    64
271105 135564 Yevgeny Aleksandrovich Zykov       M   22  172    65
271106 135565 Fernando scar Zylberberg           M   23  168    76
271107 135565 Fernando scar Zylberberg           M   27  168    76
271108 135566 James Francis "Jim" Zylker         M   21  175    75
271109 135567 Aleksandr Viktorovich Zyuzin       M   24  183    72
271110 135567 Aleksandr Viktorovich Zyuzin       M   28  183    72
271111 135568 Olga Igorevna Zyuzkova             F   33  171    69
271112 135569 Andrzej ya                         M   29  179    89
271113 135570 Piotr ya                           M   27  176    59
271114 135570 Piotr ya                           M   27  176    59
271115 135571 Tomasz Ireneusz ya                 M   30  185    96
271116 135571 Tomasz Ireneusz ya                 M   34  185    96
       Team           NOC Games       Year Season City
1      China          CHN 1992 Summer 1992 Summer Barcelona
2      China          CHN 2012 Summer 2012 Summer London
3      Denmark        DEN 1920 Summer 1920 Summer Antwerpen
4      Denmark/Sweden DEN 1900 Summer 1900 Summer Paris
5      Netherlands    NED 1988 Winter 1988 Winter Calgary
6      Netherlands    NED 1988 Winter 1988 Winter Calgary
7      Netherlands    NED 1992 Winter 1992 Winter Albertville
8      Netherlands    NED 1992 Winter 1992 Winter Albertville
9      Netherlands    NED 1994 Winter 1994 Winter Lillehammer
10     Netherlands    NED 1994 Winter 1994 Winter Lillehammer
11     United States  USA 1992 Winter 1992 Winter Albertville
12     United States  USA 1992 Winter 1992 Winter Albertville
13     United States  USA 1992 Winter 1992 Winter Albertville
14     United States  USA 1992 Winter 1992 Winter Albertville
15     United States  USA 1994 Winter 1994 Winter Lillehammer
16     United States  USA 1994 Winter 1994 Winter Lillehammer
17     United States  USA 1994 Winter 1994 Winter Lillehammer
18     United States  USA 1994 Winter 1994 Winter Lillehammer
19     United States  USA 1992 Winter 1992 Winter Albertville
20     United States  USA 1992 Winter 1992 Winter Albertville
21     United States  USA 1992 Winter 1992 Winter Albertville
22     United States  USA 1992 Winter 1992 Winter Albertville
23     United States  USA 1994 Winter 1994 Winter Lillehammer
24     United States  USA 1994 Winter 1994 Winter Lillehammer
25     United States  USA 1994 Winter 1994 Winter Lillehammer
26     United States  USA 1994 Winter 1994 Winter Lillehammer
27     Netherlands    NED 1932 Summer 1932 Summer Los Angeles
28     Netherlands    NED 1932 Summer 1932 Summer Los Angeles
29     Finland        FIN 2002 Winter 2002 Winter Salt Lake City
30     Finland        FIN 1952 Summer 1952 Summer Helsinki
â‹®      â‹®              â‹®   â‹®           â‹®    â‹®      â‹®
271087 Poland         POL 2006 Winter 2006 Winter Torino
271088 Poland         POL 1980 Summer 1980 Summer Moskva
271089 Poland         POL 1980 Summer 1980 Summer Moskva
271090 Poland         POL 2008 Summer 2008 Summer Beijing
271091 Poland         POL 2012 Summer 2012 Summer London
271092 Poland         POL 2012 Summer 2012 Summer London
271093 Poland         POL 1994 Winter 1994 Winter Lillehammer
271094 Poland         POL 1994 Winter 1994 Winter Lillehammer
271095 Poland         POL 1998 Winter 1998 Winter Nagano
271096 Poland         POL 1998 Winter 1998 Winter Nagano
271097 Poland         POL 2002 Winter 2002 Winter Salt Lake City
271098 Poland         POL 2002 Winter 2002 Winter Salt Lake City
271099 Poland         POL 2006 Winter 2006 Winter Torino
271100 Greece         GRE 2004 Summer 2004 Summer Athina
271101 Czechoslovakia TCH 1928 Summer 1928 Summer Amsterdam
271102 Czechoslovakia TCH 1972 Summer 1972 Summer Munich
271103 Russia         RUS 2000 Summer 2000 Summer Sydney
271104 Russia         RUS 2004 Summer 2004 Summer Athina
271105 Russia-1       RUS 2002 Winter 2002 Winter Salt Lake City
271106 Argentina      ARG 2000 Summer 2000 Summer Sydney
271107 Argentina      ARG 2004 Summer 2004 Summer Athina
271108 United States  USA 1972 Summer 1972 Summer Munich
271109 Russia         RUS 2000 Summer 2000 Summer Sydney
271110 Russia         RUS 2004 Summer 2004 Summer Athina
271111 Belarus        BLR 2016 Summer 2016 Summer Rio de Janeiro
271112 Poland-1       POL 1976 Winter 1976 Winter Innsbruck
271113 Poland         POL 2014 Winter 2014 Winter Sochi
271114 Poland         POL 2014 Winter 2014 Winter Sochi
271115 Poland         POL 1998 Winter 1998 Winter Nagano
271116 Poland         POL 2002 Winter 2002 Winter Salt Lake City
       Sport                Event
1      Basketball           Basketball Men's Basketball
2      Judo                 Judo Men's Extra-Lightweight
3      Football             Football Men's Football
4      Tug-Of-War           Tug-Of-War Men's Tug-Of-War
5      Speed Skating        Speed Skating Women's 500 metres
6      Speed Skating        Speed Skating Women's 1,000 metres
7      Speed Skating        Speed Skating Women's 500 metres
8      Speed Skating        Speed Skating Women's 1,000 metres
9      Speed Skating        Speed Skating Women's 500 metres
10     Speed Skating        Speed Skating Women's 1,000 metres
11     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
12     Cross Country Skiing Cross Country Skiing Men's 50 kilometres
13     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
14     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
15     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
16     Cross Country Skiing Cross Country Skiing Men's 30 kilometres
17     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
18     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
19     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
20     Cross Country Skiing Cross Country Skiing Men's 50 kilometres
21     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
22     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
23     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
24     Cross Country Skiing Cross Country Skiing Men's 30 kilometres
25     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
26     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
27     Athletics            Athletics Women's 100 metres
28     Athletics            Athletics Women's 4 x 100 metres Relay
29     Ice Hockey           Ice Hockey Men's Ice Hockey
30     Swimming             Swimming Men's 400 metres Freestyle
â‹®      â‹®                    â‹®
271087 Figure Skating       Figure Skating Mixed Ice Dancing
271088 Swimming             Swimming Men's 100 metres Butterfly
271089 Swimming             Swimming Men's 200 metres Butterfly
271090 Sailing              Sailing Men's Two Person Keelboat
271091 Sailing              Sailing Men's Two Person Keelboat
271092 Volleyball           Volleyball Men's Volleyball
271093 Speed Skating        Speed Skating Men's 1,500 metres
271094 Speed Skating        Speed Skating Men's 5,000 metres
271095 Speed Skating        Speed Skating Men's 1,500 metres
271096 Speed Skating        Speed Skating Men's 5,000 metres
271097 Speed Skating        Speed Skating Men's 5,000 metres
271098 Speed Skating        Speed Skating Men's 10,000 metres
271099 Speed Skating        Speed Skating Men's 5,000 metres
271100 Wrestling            Wrestling Women's Middleweight, Freestyle
271101 Athletics            Athletics Men's Marathon
271102 Cycling              Cycling Men's Team Pursuit, 4,000 metres
271103 Athletics            Athletics Women's 4 x 400 metres Relay
271104 Athletics            Athletics Women's 4 x 400 metres Relay
271105 Luge                 Luge Mixed (Men)'s Doubles
271106 Hockey               Hockey Men's Hockey
271107 Hockey               Hockey Men's Hockey
271108 Football             Football Men's Football
271109 Rowing               Rowing Men's Lightweight Coxless Fours
271110 Rowing               Rowing Men's Lightweight Coxless Fours
271111 Basketball           Basketball Women's Basketball
271112 Luge                 Luge Mixed (Men)'s Doubles
271113 Ski Jumping          Ski Jumping Men's Large Hill, Individual
271114 Ski Jumping          Ski Jumping Men's Large Hill, Team
271115 Bobsleigh            Bobsleigh Men's Four
271116 Bobsleigh            Bobsleigh Men's Four
       Medal
1      NA
2      NA
3      NA
4      Gold
5      NA
6      NA
7      NA
8      NA
9      NA
10     NA
11     NA
12     NA
13     NA
14     NA
15     NA
16     NA
17     NA
18     NA
19     NA
20     NA
21     NA
22     NA
23     NA
24     NA
25     NA
26     NA
27     NA
28     NA
29     NA
30     NA
â‹®      â‹®
271087 NA
271088 NA
271089 NA
271090 NA
271091 NA
271092 NA
271093 NA
271094 NA
271095 NA
271096 NA
271097 NA
271098 NA
271099 NA
271100 NA
271101 NA
271102 NA
271103 Bronze
271104 Silver
271105 NA
271106 NA
271107 NA
271108 NA
271109 NA
271110 NA
271111 NA
271112 NA
271113 NA
271114 NA
271115 NA
271116 NA

__1. How old were the youngest male and female participants of the 1996 Olympics?__

- 16 and 15
- **14 and 12**
- 16 and 12
- 13 and 11

In [2]:
library("magrittr")
library("sjm")

In [14]:
min(df[df['Sex'] == 'F'& df['Games'] == '1996 Summer', 'Age'], na.rm=T)

[1] 12

In [15]:
min(df[df['Sex'] == 'M'& df['Games'] == '1996 Summer', 'Age'], na.rm=T)

[1] 14

__2. What was the percentage of male gymnasts among all the male participants of the 2000 Olympics? Round the answer to the first decimal.__

*Hint:* here and further if needed drop duplicated sportsmen to count only unique ones. 

- 0.2
- **1.5** 
- 2.5
- 7.7

In [26]:
needed <- df[!duplicated(df$Name),]
gymnasts <- needed[needed['Sport'] == 'Gymnastics' & needed['Games'] == '2000 Summer' & needed['Sex'] == 'M', ]
sportsmen <- needed[needed['Games'] == '2000 Summer' & needed['Sex'] == 'M',]
sportsmen

       ID     Name                                   Sex Age Height Weight
32      12    Jyri Tapani Aalto                      M   31  172     70
58      18    Timo Antero Aaltonen                   M   31  189    130
82      23    Fritz Aanes                            M   22  187     89
147     53    Talaat Abada                           M   24  172     58
166     68    Pablo Martn Abal                       M   23  178     76
169     70    Jess Iory Aball Martnez                M   26  167     65
179     76    Jouan Patrice Abanda Etong             M   22  185     82
185     82    Enrique Abaroa Martnez                 M   26  183     75
243    118    Mahmoud Abbas                          M   22  165     65
248    123    Sohail Abbas                           M   25  178     80
263    134    Christian Abbiati                      M   23  192     90
265    136    Alessandro Abbio                       M   29  195     85
286    152    Matt Abbott                            M   34  185     91
289    155    Mohamed Ibrahim Abd El-Fatah Mohamed   M   22  185     98
319    171    Mahmoud Abdel Aziz                     M   25  174     70
320    172    Mohamed Abdel Ellah                    M   32  168     68
325    177    Mohamed Abdel Fattah                   M   23  174     69
391    216    Kamal Abdel Rehim                      M   26  190     95
392    217    Reskalla Mohamed Abdel Rehim           M   22  165     48
393    218    Ahmed Ali Abdel Samad                  M   27  195     95
438    244    Raouf Abdelraouf                       M   22  167     63
467    256    Abdihakim "Abdi" Abdirahman            M   23  178     61
471    257    Ali Abdo                               M   19  169     74
482    264    Justin Abdou                           M   29  175     85
496    275    Bashir Abdullah Abdul Aziz             M   22  180     73
505    280    Mohamed Abdul Hamid                    M   19  175     55
610    351    Julius Shareef Abdur-Rahim             M   23  202    104
644    371    Shinnosuke Abe                         M   21  179     91
652    376    Yoshiyuki Abe                          M   31  175     67
721    411    Gezahgne Abera                         M   22  166     58
â‹®      â‹®      â‹®                                      â‹®   â‹®   â‹®      â‹®
269263 134734 Zheng Lihui                            M   22  158     52
269314 134760 Yevgeny Anatolyevich Zhilyayev         M   27  190     91
269324 134766 Askhat Rasulovich Zhitkeyev            M   19  187    100
269341 134769 Denis Yevgenyevich Zhivchikov          M   24  191     95
269463 134830 Zhou Yuanguo                           M   22  174     68
269478 134839 Zhu Feng                               M   17  191     83
269520 134863 Zhu Yi                                 M   22  177     85
269556 134878 Vitaly Ivanovich Zhuk                  M   27  166     63
269584 134893 Mansur Zhumayev                        M   25  170     66
269594 134897 Konstantin Borisovich Zhuravlyov       M   24  180     70
269595 134898 Oleg Borisovich Zhuravlyov             M   18  184     74
269912 135043 Nenad Zimonji                          M   24  190     92
269946 135056 Oleksandr Borysovych Zinenko           M   21  184     85
270010 135079 Irek Khaydarovich Zinnurov             M   31  187     84
270101 135124 Yevhen Volodymyrovych Ziukov           M   22  182     74
270130 135142 Mehman Akif zizov                      M   24  182     81
270284 135207 Giancarlo Zolezzi Seoane               M   19  195     85
270367 135244 Dragan Zori                            M   21  193     92
270483 135291 Roman Volodymyrovych Zozulia           M   21  164     59
270545 135311 Attila Zsivczky                        M   23  193     82
270646 135358 Oleksandr Valeriyovych Zubrikhin       M   25  180     75
270713 135382 Eli Zuckerman                          M   27  177     60
270729 135394 Niels Zuidweg                          M   26  190     90
270730 135395 Wilhelmus Gerardus "Wilco" Zuijderwijk M   30  191     90
270732 135396 Martijn Hendrik Zuijdweg               M   23  186     83
270821 135444 Juan Zunzunegui Guimerans              M   24  177     70
270848 135458 Rami Zur                               M   23  175     77
271012 135522 Klaas Erik "Klaas-Erik" Zwering        M   19  189     80
271106 135565 Fernando scar Zylberberg               M   23  168     76
271109 135567 Aleksandr Viktorovich Zyuzin           M   24  183     72
       Team                  NOC Games       Year Season City   Sport
32     Finland               FIN 2000 Summer 2000 Summer Sydney Badminton
58     Finland               FIN 2000 Summer 2000 Summer Sydney Athletics
82     Norway                NOR 2000 Summer 2000 Summer Sydney Wrestling
147    Egypt                 EGY 2000 Summer 2000 Summer Sydney Taekwondo
166    Argentina             ARG 2000 Summer 2000 Summer Sydney Swimming
169    Cuba                  CUB 2000 Summer 2000 Summer Sydney Diving
179    Cameroon              CMR 2000 Summer 2000 Summer Sydney Football
185    Mexico                MEX 2000 Summer 2000 Summer Sydney Tennis
243    Egypt                 EGY 2000 Summer 2000 Summer Sydney Cycling
248    Pakistan              PAK 2000 Summer 2000 Summer Sydney Hockey
263    Italy                 ITA 2000 Summer 2000 Summer Sydney Football
265    Italy                 ITA 2000 Summer 2000 Summer Sydney Basketball
286    Canada                CAN 2000 Summer 2000 Summer Sydney Sailing
289    Egypt                 EGY 2000 Summer 2000 Summer Sydney Wrestling
319    Egypt                 EGY 2000 Summer 2000 Summer Sydney Volleyball
320    Egypt                 EGY 2000 Summer 2000 Summer Sydney Shooting
325    Egypt                 EGY 2000 Summer 2000 Summer Sydney Cycling
391    Egypt                 EGY 2000 Summer 2000 Summer Sydney Rowing
392    Egypt                 EGY 2000 Summer 2000 Summer Sydney Boxing
393    Egypt                 EGY 2000 Summer 2000 Summer Sydney Boxing
438    Egypt                 EGY 2000 Summer 2000 Summer Sydney Gymnastics
467    United States         USA 2000 Summer 2000 Summer Sydney Athletics
471    Australia             AUS 2000 Summer 2000 Summer Sydney Wrestling
482    Canada                CAN 2000 Summer 2000 Summer Sydney Wrestling
496    Kuwait                KUW 2000 Summer 2000 Summer Sydney Football
505    Sudan                 SUD 2000 Summer 2000 Summer Sydney Swimming
610    United States         USA 2000 Summer 2000 Summer Sydney Basketball
644    Japan                 JPN 2000 Summer 2000 Summer Sydney Baseball
652    Japan                 JPN 2000 Summer 2000 Summer Sydney Cycling
721    Ethiopia              ETH 2000 Summer 2000 Summer Sydney Athletics
â‹®      â‹®                     â‹®   â‹®           â‹®    â‹®      â‹®      â‹®
269263 China                 CHN 2000 Summer 2000 Summer Sydney Gymnastics
269314 Kazakhstan            KAZ 2000 Summer 2000 Summer Sydney Water Polo
269324 Kazakhstan            KAZ 2000 Summer 2000 Summer Sydney Judo
269341 Kazakhstan            KAZ 2000 Summer 2000 Summer Sydney Water Polo
269463 China                 CHN 2000 Summer 2000 Summer Sydney Sailing
269478 China                 CHN 2000 Summer 2000 Summer Sydney Taekwondo
269520 China                 CHN 2000 Summer 2000 Summer Sydney Swimming
269556 Belarus               BLR 2000 Summer 2000 Summer Sydney Wrestling
269584 Uzbekistan            UZB 2000 Summer 2000 Summer Sydney Judo
269594 Uzbekistan            UZB 2000 Summer 2000 Summer Sydney Athletics
269595 Uzbekistan            UZB 2000 Summer 2000 Summer Sydney Athletics
269912 Serbia and Montenegro SCG 2000 Summer 2000 Summer Sydney Tennis
269946 Ukraine               UKR 2000 Summer 2000 Summer Sydney Shooting
270010 Russia                RUS 2000 Summer 2000 Summer Sydney Water Polo
270101 Ukraine               UKR 2000 Summer 2000 Summer Sydney Athletics
270130 Azerbaijan            AZE 2000 Summer 2000 Summer Sydney Judo
270284 Chile                 CHI 2000 Summer 2000 Summer Sydney Swimming
270367 Serbia and Montenegro SCG 2000 Summer 2000 Summer Sydney Canoeing
270483 Ukraine               UKR 2000 Summer 2000 Summer Sydney Gymnastics
270545 Hungary               HUN 2000 Summer 2000 Summer Sydney Athletics
270646 Ukraine               UKR 2000 Summer 2000 Summer Sydney Boxing
270713 Israel                ISR 2000 Summer 2000 Summer Sydney Sailing
270729 Netherlands           NED 2000 Summer 2000 Summer Sydney Water Polo
270730 Netherlands           NED 2000 Summer 2000 Summer Sydney Cycling
270732 Netherlands           NED 2000 Summer 2000 Summer Sydney Swimming
270821 Spain                 ESP 2000 Summer 2000 Summer Sydney Rowing
270848 Israel                ISR 2000 Summer 2000 Summer Sydney Canoeing
271012 Netherlands           NED 2000 Summer 2000 Summer Sydney Swimming
271106 Argentina             ARG 2000 Summer 2000 Summer Sydney Hockey
271109 Russia                RUS 2000 Summer 2000 Summer Sydney Rowing
       Event                                          Medal
32     Badminton Men's Singles                        NA
58     Athletics Men's Shot Put                       NA
82     Wrestling Men's Light-Heavyweight, Greco-Roman NA
147    Taekwondo Men's Flyweight                      NA
166    Swimming Men's 100 metres Butterfly            NA
169    Diving Men's Platform                          NA
179    Football Men's Football                        Gold
185    Tennis Men's Doubles                           NA
243    Cycling Men's Road Race, Individual            NA
248    Hockey Men's Hockey                            NA
263    Football Men's Football                        NA
265    Basketball Men's Basketball                    NA
286    Sailing Mixed Three Person Keelboat            NA
289    Wrestling Men's Light-Heavyweight, Greco-Roman NA
319    Volleyball Men's Volleyball                    NA
320    Shooting Men's Air Rifle, 10 metres            NA
325    Cycling Men's Road Race, Individual            NA
391    Rowing Men's Coxless Fours                     NA
392    Boxing Men's Light-Flyweight                   NA
393    Boxing Men's Super-Heavyweight                 NA
438    Gymnastics Men's Individual All-Around         NA
467    Athletics Men's 10,000 metres                  NA
471    Wrestling Men's Welterweight, Greco-Roman      NA
482    Wrestling Men's Light-Heavyweight, Freestyle   NA
496    Football Men's Football                        NA
505    Swimming Men's 50 metres Freestyle             NA
610    Basketball Men's Basketball                    Gold
644    Baseball Men's Baseball                        NA
652    Cycling Men's Road Race, Individual            NA
721    Athletics Men's Marathon                       Gold
â‹®      â‹®                                              â‹®
269263 Gymnastics Men's Individual All-Around         NA
269314 Water Polo Men's Water Polo                    NA
269324 Judo Men's Half-Heavyweight                    NA
269341 Water Polo Men's Water Polo                    NA
269463 Sailing Men's Windsurfer                       NA
269478 Taekwondo Men's Heavyweight                    NA
269520 Swimming Men's 100 metres Breaststroke         NA
269556 Wrestling Men's Lightweight, Greco-Roman       NA
269584 Judo Men's Half-Lightweight                    NA
269594 Athletics Men's 4 x 100 metres Relay           NA
269595 Athletics Men's 4 x 100 metres Relay           NA
269912 Tennis Men's Doubles                           NA
269946 Shooting Men's Running Target, 10 metres       NA
270010 Water Polo Men's Water Polo                    Silver
270101 Athletics Men's 4 x 400 metres Relay           NA
270130 Judo Men's Half-Middleweight                   NA
270284 Swimming Men's 400 metres Freestyle            NA
270367 Canoeing Men's Kayak Fours, 1,000 metres       NA
270483 Gymnastics Men's Individual All-Around         NA
270545 Athletics Men's Decathlon                      NA
270646 Boxing Men's Middleweight                      NA
270713 Sailing Men's Two Person Dinghy                NA
270729 Water Polo Men's Water Polo                    NA
270730 Cycling Men's Team Pursuit, 4,000 metres       NA
270732 Swimming Men's 200 metres Freestyle            NA
270821 Rowing Men's Lightweight Double Sculls         NA
270848 Canoeing Men's Kayak Doubles, 500 metres       NA
271012 Swimming Men's 200 metres Backstroke           NA
271106 Hockey Men's Hockey                            NA
271109 Rowing Men's Lightweight Coxless Fours         NA

In [42]:
print(nrow(gymnasts) / nrow(sportsmen) * 100)

[1] 1.462264

__3. What are the mean and standard deviation of height for female basketball players participated in the 2000 Olympics? Round the answer to the first decimal.__

- 178.5 and 7.2
- 179.4 and 10
- 180.7 and 6.7
- **182.4 and 9.1**

In [39]:
#df <- df[!duplicated(df$Name),]
needed <- df[df['Sex'] == 'F' & df['Sport'] == 'Basketball' & df['Games'] == '2000 Summer', ]

In [40]:
lapply(needed['Height'], mean, na.rm = TRUE)

$Height
[1] 182.3873

In [43]:
lapply(needed['Height'], sd, na.rm = TRUE)

$Height
[1] 9.139462

__4. Find a sportsperson participated in the 2002 Olympics, with the highest weight among other participants of the same Olympics. What sport did he or she do?__

- Judo
- **Bobsleigh**
- Weightlifting
- Boxing

In [66]:
needed = df[df['Weight'] == lapply(df[df['Games'] == '2002 Winter', ]['Weight'], max, na.rm=TRUE) & df['Games'] == '2002 Winter',]['Sport']

In [67]:
needed[!is.na(needed['Sport']), 'Sport']

[1] Bobsleigh
66 Levels: Aeronautics Alpine Skiing Alpinism Archery ... Wrestling

__5. How many times did Pawe Abratkiewicz participate in the Olympics held in different years?__

- 0
- 1 
- 2
- ***3***

In [82]:
needed = df[df['Name'] == 'Pawe Abratkiewicz' ,]
nrow(needed[!duplicated(needed$Games), ])

[1] 3

__6. How many silver medals in tennis did Australia win at the 2000 Olympics?__

- 0
- 1 
- **2** 
- 3

In [89]:
needed <- df[df['Team'] == 'Australia' & df['Medal'] == 'Silver' & df['Games'] == '2000 Summer' & df['Sport'] == 'Tennis', ]

In [95]:
nrow(needed[!is.na(needed$ID),])

[1] 2

__7. Is it true that Switzerland won fewer medals than Serbia at the 2016 Olympics? Do not consider NaN values in _Medal_ column.__ 

- **Yes** 
- No

In [98]:
sw <- df[df['Team'] == 'Switzerland' & !is.na(df['Medal']) & df['Games'] == '2016 Summer', ]
sb <- df[df['Team'] == 'Serbia' & !is.na(df['Medal']) & df['Games'] == '2016 Summer', ]

In [99]:
nrow(sw) < nrow(sb)

[1] TRUE

__8. What age category did the fewest and the most participants of the 2014 Olympics belong to?__
- [45-55] and [25-35) correspondingly
- **[45-55] and [15-25) correspondingly**
- [35-45] and [25-35) correspondingly
- [45-55] and [35-45) correspondingly

In [102]:
elder = df[(55 >= df['Age']) & (df['Age'] >= 45), ]
adults = df[(45 >= df['Age']) & (df['Age'] >= 35), ]
print(nrow(elder) < nrow(adults))
young = df[(25 > df['Age']) & (df['Age'] >= 15), ]
adults = df[(45 > df['Age']) & (df['Age'] >= 35),]
medium = df[(35 > df['Age']) & (df['Age'] >= 25),]
print((nrow(young) > nrow(medium)) && (nrow(young) > nrow(adults)))

[1] TRUE
[1] TRUE

__9. Is it true that there were Summer Olympics held in Lake Placid? Is it true that there were Winter Olympics held in Sankt Moritz?__

- Yes, Yes
- Yes, No
- **No, Yes** 
- No, No

In [20]:
print(nrow(df[(df['City'] == 'Lake Placid') & (df$Season == 'Summer'),]) > 0)
print(nrow(df[(df['City'] == 'Sankt Moritz') & (df$Season == 'Winter'),]) > 0)

[1] FALSE
[1] TRUE

__10. What is the absolute difference between the number of unique sports at the 1995 Olympics and 2016 Olympics?__

- 16
- 24
- 26
- **34**

In [47]:
#df = df[!duplicated(df['Sport']),]
s1995 = df[df['Year'] == 1995, ]

s2016 =  df[df['Year']== 2016, ]

print(nrow(s1995[!duplicated(s1995['Sport']),]) - nrow(s2016[!duplicated(s2016['Sport']),]))

[1] -34